---
- name: Backup router configurations
  hosts: asr
  connection: local
  gather_facts: no

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: cisco
      password: cisco

  tasks:
    # Collect all facts from the device
    - ios_facts:
        gather_subset: all
        provider: "{{ cli }}"


