---
- name: Configure ASR routers
  hosts: asr
  gather_facts: false
  connection: local

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: cisco
      password: cisco

  - name: load new acl into device
    ios_config:
      lines:
        - 10 permit ip host 1.1.1.1 any log
        - 20 permit ip host 2.2.2.2 any log
        - 30 permit ip host 3.3.3.3 any log
        - 40 permit ip host 4.4.4.4 any log
        - 50 permit ip host 5.5.5.5 any log
      parents: ip access-list extended ansible_acl
      before: no ip access-list extended ansible_acl
      match: exact
      provider: "{{ cli }}"

  - name: configure interface settings
    ios_config:
      lines:
        - description test interface
        - ip address 172.31.1.1 255.255.255.0
      parents: interface loopback 100
      provider: "{{ cli }}"

  - name: save running to startup when modified
    ios_config:
      save_when: modified
